Update JVM from 11 to 17

diff --git a/compiler/release b/compiler/release
--- a/compiler/release
+++ b/compiler/release
@@ -7,7 +7,7 @@
 #
 # 1. Install GraalVM and native-image.
 #
-# 2. Set the environment variable GRAALVM_JAVA_HOME.
+# 2. Set the environment variable FPP_GRAALVM_JAVA_HOME.
 #
 # 3. To pass flags to native-image, set the environment variable
 #    FPP_NATIVE_IMAGE_FLAGS.
@@ -43,10 +43,10 @@ print_phase()
   echo "----------------------------------------------------------------------"
 }
 
-# Check that GRAALVM_JAVA_HOME is set
-if test -z "$GRAALVM_JAVA_HOME"
+# Check that FPP_GRAALVM_JAVA_HOME is set
+if test -z "$FPP_GRAALVM_JAVA_HOME"
 then
-  echo "[ERROR] Environment variable GRAALVM_JAVA_HOME is not set" 1>&2
+  echo "[ERROR] Environment variable FPP_GRAALVM_JAVA_HOME is not set" 1>&2
   exit 1
 fi
 
@@ -55,7 +55,7 @@ cd `dirname $0`
 
 # Set local variables
 native_bin="native-fpp-`uname`-`uname -m`"
-native_image="$GRAALVM_JAVA_HOME/bin/native-image"
+native_image="$FPP_GRAALVM_JAVA_HOME/bin/native-image"
 meta_inf_dir="lib/src/main/resources/META-INF/native-image"
 release_tgz="$native_bin.tar.gz"
 # Use gtar if it's available
