Revise release script

diff --git a/compiler/release b/compiler/release
--- a/compiler/release
+++ b/compiler/release
@@ -12,15 +12,38 @@
 # See README.adoc.
 # ----------------------------------------------------------------------
 
+# Print and evaluate
+evalp()
+{
+  echo "$@"
+  $@
+}
+
+# Get tool names from a directory
+get_tool_names()
+{
+  dir=$1
+  for file in $dir/*.jar
+  do
+    basename $file .jar
+  done
+}
+
+# Check that GRAALVM_JAVA_HOME is set
 if test -z "$GRAALVM_JAVA_HOME"
 then
   echo "release: environment variable GRAALVM_JAVA_HOME is not set" 1>&2
   exit 1
 fi
-directory=`dirname $0`
-native_bin="$directory/native-fpp-`uname`-`uname -m`"
+
+# Run in the directory where this script is located
+cd `dirname $0`
+
+# Set local variables
+native_bin="native-fpp-`uname`-`uname -m`"
+java=$GRAALVM_JAVA_HOME/bin/java
 native_image="$GRAALVM_JAVA_HOME/bin/native-image"
-meta_inf_dir="$directory/lib/src/main/resources/META-INF/native-image/"
+meta_inf_dir="lib/src/main/resources/META-INF/native-image/"
 
 # Make directories
 mkdir -p "$meta_inf_dir"
@@ -30,34 +53,33 @@ mkdir -p "$native_bin"
 echo "C compiler version"
 cc --version
 echo "Java version"
-java --version
+$java --version
 echo "Native Image Version"
-native-image --version
+$native_image --version
 
+# Install jar files in bin
+./install-trace
 
-# Install jar files here
-$directory/install-trace
-# Test a run before running test
-$directory/bin/fpp-locate-defs tools/fpp-locate-defs/test/defs/defs-1.fpp tools/fpp-locate-defs/test/defs/defs-2.fpp 1>/dev/null
+# Get the tool names from bin
+tool_names=`get_tool_names bin`
+
+# Run unit tests and capture the GraalVM trace
+./test
 if [ $? -ne 0 ]
 then
-    echo "[ERROR] Failed to run JAR with tracing enabled"
+    # Check that unit tests passed
+    echo "[ERROR] JVM unit tests failed"
     exit 1
 fi
-
-# Trace through testing
-$directory/test
-if [ $? -ne 0 ]
-then
-    echo "[WARNING] Failed to run tests"
-fi
 sync; sync; sync;
-# Convert jar files to binaries
-for jar_file in $directory/bin/*.jar
+
+# Use GraalVM to convert jar files to binaries
+for jar_file in bin/*.jar
 do
     out_file=$native_bin/`basename $jar_file .jar`
     echo "Building $out_file"
-    "$native_image" --configure-reflection-metadata --no-fallback --install-exit-handlers -jar "$jar_file" "$out_file"
+    evalp "$native_image" --configure-reflection-metadata --no-fallback \
+      --install-exit-handlers -jar "$jar_file" "$out_file"
     if [ $? -ne 0 ]
     then
         echo "release: Failed to build $out_file"
@@ -73,26 +95,36 @@ done
 sync; sync; sync;
 
 # Clean up native directory
-rm "$native_bin"/*.txt
+rm -f "$native_bin"/*.txt "$native_bin"/*.o
 sync; sync; sync;
 
-# Testing of the native binaries
-rm -r "$directory/bin"
-cp -r "$native_bin" "$directory/bin"
-"$directory/test"
+# Test the native binaries
+evalp rm -r "bin"
+evalp cp -r "$native_bin" "bin"
+./test
 if [ $? -ne 0 ]
 then
-    echo "[WARNING] Failed to run tests"
+    echo "[ERROR] Native unit tests failed"
+    exit 1
 fi
 
-# Create tar ball
+# Create the tar ball
 release_tgz="$native_bin.tar.gz"
-tar -czf "$release_tgz" "$native_bin"
+evalp tar -czf "$release_tgz" "$native_bin"
 sync; sync; sync;
-# Check if file size too small
-if [ `stat -f %z $release_tgz` -lt 55846858 ]
-then
-    echo "Release archive $release_tgz too small with size `du -hs $release_tgz`"
-    exit 99
-fi
+
+# Verify the tar ball
+mkdir -p check-tar
+(cd check-tar; evalp tar -xvf "../$release_tgz")
+sync; sync; sync;
+for file in `ls "$native_bin"`
+do
+  if ! evalp diff -q "$native_bin/$file check-tar/$native_bin/$file"
+  then
+    echo "[ERROR] Archive creation failed"
+    exit 1
+  fi
+done
+
+# Print status
 echo "Release archive written to $release_tgz with size `du -hs $release_tgz`"
