Revise test script

diff --git a/compiler/test b/compiler/test
--- a/compiler/test
+++ b/compiler/test
@@ -4,24 +4,26 @@
 
 num_failed=0
 
-tests=`find . -name run | grep test | sed 's;^\./;;'`
-for t in $tests
-do
-  echo "[ $t ]"
-  dir=`dirname $t`
-  base=`basename $t`
-  (cd $dir; ./$base)
-  num_failed=`expr $num_failed + $?`
-done
+{
+  tests=`find . -name run | grep test | sed 's;^\./;;'`
+  for t in $tests
+  do
+    echo "[ $t ]"
+    dir=`dirname $t`
+    base=`basename $t`
+    (cd $dir; ./$base)
+    num_failed=`expr $num_failed + $?`
+  done
 
-echo 
-if test $num_failed -eq 0
-then
-  printf "All tests "
-  echo_green PASSED
-else
-  printf "$num_failed tests "
-  echo_red FAILED
-fi
+  echo 
+  if test $num_failed -eq 0
+  then
+    printf "All tests "
+    echo_green PASSED
+  else
+    printf "$num_failed tests "
+    echo_red FAILED
+  fi
+} 2>&1 | tee test-output.txt
 
 exit $num_failed
